import { Geist,Poppins } from "next/font/google";
import "./css/globals.css";
import Navigation from "./components/home-components/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Believe Fitness",
  description: "Generated by create next app",
};

export default function RootLayout({ children}) {
  return (
    <html lang="en">
      <body
        className={`relative ${poppins.variable} ${geistSans.variable} antialiased`}
      >
        <main>
          <header className="grid grid-cols-2 p-4 absolute top-4 right-4 z-50 w-full">
            <div className="col-span-2">
            <Navigation />
            </div>
          </header>
          {children}
        </main>
      </body>
    </html>
  );
}
