import { Geist,Poppins } from "next/font/google";
import "./css/globals.css";
import { getCookiesValues } from "./lib/dal/cookiesStore";
import Navigation from "./components/global-components/Navigation";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Believe Fitness",
  description: "Generated by create next app",
};

export default async function RootLayout({ children}) {
  const {token } = await getCookiesValues();
  
  return (
    <html lang="en">
      <body
        className={`relative ${poppins.variable} ${geistSans.variable} antialiased`}>
        <main>
          <header className="grid grid-cols-2 p-4 absolute top-4 right-4 z-50 w-full">
            <div className="col-span-2">
            <Navigation token={token} />
            </div>
          </header>
          {children}
        </main>
        <ToastContainer />
      </body>
    </html>
  );
}
